### ISSUE TITLE
Saturn DL not working

### ISSUE THREAD

**Issue by jupiter50** [mess110/coinmarketcap.northpole.ro#36]
Hi,

This might be related to the server issues but having issues downloading the JSON history files:

Using backup/api/v8/history/
Found 1197 coins and 3050 files.
/usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/json/common.rb:155:in `parse': 757: unexpected token at '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> (JSON::ParserError)
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator,
 [no address given] and inform them of the time the error occurred,
and anything you might have done that may have
caused the error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.2.22 (Ubuntu) Server at coinmarketcap.northpole.ro Port 80</address>
</body></html>
'
        from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/json/common.rb:155:in `parse'
        from ./saturn.rb:36:in `req'
        from ./saturn.rb:146:in `block (2 levels) in download_history'
        from ./saturn.rb:144:in `each'
        from ./saturn.rb:144:in `block in download_history'
        from ./saturn.rb:143:in `each'
        from ./saturn.rb:143:in `download_history'
        from ./saturn.rb:215:in `<main>'

**Comment by mess110** [comment]
Will check, thx

**Comment by mess110** [comment]
Added some rescue statements, can you please check if it works now? Some coins contain invalid json again :(

I really suspect its the disk IO :(

**Comment by jupiter50** [comment]
Just running it now, looks like it logs out the error and continues on instead of just bombing out which is better! Taking a quick look, it looks like mainly the 14 day JSONs it errors on

Disk io problems suck :( Will let you know if it it does anything else before it completes

**Comment by jupiter50** [comment]
I think I just killed your server. Sorry! :(

Error Connection timed out - connect(2) for "coinmarketcap.northpole.ro" port 80 parsing http://coinmarketcap.northpole.ro/history.json?coin=sync&period=2016&format=hash

**Comment by mess110** [comment]
Hahaha, no worries you didn't kill the server. Its a puny server, if something actually killed it, it was my choice to use the cheapest hosting package.

It is restarting now, should be back online soon

**Comment by jupiter50** [comment]
Thanks that worked. Just tried running the "normal" saturn part after having the download done and i get this:

./saturn.rb:95:in `block in run_script': undefined method `values' for nil:NilClass (NoMethodError)
        from ./saturn.rb:91:in `each'
        from ./saturn.rb:91:in `run_script'
        from ./saturn.rb:218:in `<main>'
